### ISSUE TITLE
Full path to checkpoint file?

### ISSUE THREAD

**Issue by gha2012** [ikalvet/heme_binder_diffusion#12]
Hi, 
thank you so much for making this available!
I am trying to get this to run on my server and get an error message during the diffusion step:

```
Error executing job with overrides: ['inference.input_pdb=/home/gha/heme_binder_diffusion/input/7o2g.pdb', 'inference.output_prefix=./out/7o2g_dif']
Traceback (most recent call last):
  File "/home/gha/rf_diffusion_all_atom/run_inference.py", line 74, in main
    sampler = get_sampler(conf)
  File "/home/gha/rf_diffusion_all_atom/run_inference.py", line 96, in get_sampler
    sampler = inference.model_runners.sampler_selector(conf)
  File "/home/gha/rf_diffusion_all_atom/inference/model_runners.py", line 358, in sampler_selector
    sampler = NRBStyleSelfCond(conf)
  File "/home/gha/rf_diffusion_all_atom/inference/model_runners.py", line 41, in __init__
    self.initialize(conf)
  File "/home/gha/rf_diffusion_all_atom/inference/model_runners.py", line 59, in initialize
    self.load_checkpoint()
  File "/home/gha/rf_diffusion_all_atom/inference/model_runners.py", line 123, in load_checkpoint
    self.ckpt  = torch.load(
  File "/home/gha/miniconda3/envs/diffusionAA/lib/python3.9/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/gha/miniconda3/envs/diffusionAA/lib/python3.9/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/gha/miniconda3/envs/diffusionAA/lib/python3.9/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'RFDiffusionAA_paper_weights.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I am sure it has to do with this line in the instructions, but I do not understand what I need to do here...

```
RFdiffusionAA:
Download RFdiffusionAA from here: https://github.com/baker-laboratory/rf_diffusion_all_atom
and follow its instructions.
Make sure to provide a full path to the checkpoint file in this configuration file:
rf_diffusion_all_atom/config/inference/aa.yaml
```

Any tips? Thank you very much!

**Comment by ikalvet** [comment]
Have you downloaded the weights following this link?
`wget http://files.ipd.uw.edu/pub/RF-All-Atom/weights/RFDiffusionAA_paper_weights.pt`

And subsequently provided a full path of that `.pt` file in here: `/home/gha/rf_diffusion_all_atom/config/inference/aa.yaml` ?
The line you would need to update is `  ckpt_path: RFDiffusionAA_paper_weights.pt`

Hope this helps!

**Comment by gha2012** [comment]
Ahh! That was it! Thank you very much!
