### ISSUE TITLE
REMARK 666 not copied to designed files?

### ISSUE THREAD

**Issue by gha2012** [ikalvet/heme_binder_diffusion#13]
Hi,
I am trying to follow the pipeline without inpainting and I am running into an error in the ligMPNN step.
Below is the output from the slurm job. The problem is that catres is an empty list. I found that in several places, the script checks for the catalytic residue corresponding to A15 in the original structure. If I haven't overlooked something, the REMARK 666 line from the input PDB is not copied into the diffused models when the inpainting steps are skipped. Is this intended or is this a bug?
Thank you for your help,
Gregor

```
Traceback (most recent call last):
  File "/home/gha/heme_binder_diffusion/scripts/design/heme_pocket_ligMPNN.py", line 470, in <module>
    scores_df = scoring.score_design(_pose2, pyrosetta.get_fa_scorefxn(), catalytic_resnos)
  File "/home/gha/heme_binder_diffusion/scripts/design/scoring/heme_scoring.py", line 57, in score_design
    df_scores.at[0, 'corrected_ddg'] = calculate_ddg(pose, sfx, catres[0])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/gha/heme_binder_diffusion/scripts/design/heme_pocket_ligMPNN.py", line 470, in <module>
    scores_df = scoring.score_design(_pose2, pyrosetta.get_fa_scorefxn(), catalytic_resnos)
  File "/home/gha/heme_binder_diffusion/scripts/design/scoring/heme_scoring.py", line 57, in score_design
    df_scores.at[0, 'corrected_ddg'] = calculate_ddg(pose, sfx, catres[0])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/gha/heme_binder_diffusion/scripts/design/heme_pocket_ligMPNN.py", line 470, in <module>
    scores_df = scoring.score_design(_pose2, pyrosetta.get_fa_scorefxn(), catalytic_resnos)
  File "/home/gha/heme_binder_diffusion/scripts/design/scoring/heme_scoring.py", line 57, in score_design
    df_scores.at[0, 'corrected_ddg'] = calculate_ddg(pose, sfx, catres[0])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/gha/heme_binder_diffusion/scripts/design/heme_pocket_ligMPNN.py", line 470, in <module>
    scores_df = scoring.score_design(_pose2, pyrosetta.get_fa_scorefxn(), catalytic_resnos)
  File "/home/gha/heme_binder_diffusion/scripts/design/scoring/heme_scoring.py", line 57, in score_design
    df_scores.at[0, 'corrected_ddg'] = calculate_ddg(pose, sfx, catres[0])
IndexError: list index out of range
```

**Comment by ikalvet** [comment]
Thank you for trying it! Unfortunately I cannot reproduce this issue when I run this pipeline myself. I noticed a few other small bugs in the process and will push an update soon, but nothing that would could the issue you had. Is there a chance that some step got skipped over? All of the processing scripts should carry the REMARK 666 lines forward otherwise.
