### ISSUE TITLE
 [Analyzing diffusion outputs] Error occurred when trying to normalize the vector between points A and B.  A=[0.000000,0.000000,0.000000], B=[0.000000,0.000000,0.000000].

### ISSUE THREAD

**Issue by Lyueyang2020** [ikalvet/heme_binder_diffusion#18]
I tried to use your pipeline. in the [Analyzing diffusion outputs] section of 0diffusion, the following error occurs. I tried to use your 7o2g_HBA.pdb with small molecule HBA and it works fine, I don't know which part of the process may be the problem, I didn't find any abnormality by checking the structure of the pdb . Because both my small molecule and HBA produced pdb files contain “0.000 0.000 0.000” coordinates, but the HBA produced protein can run normally without “0.000 0.000 0.000 0.000” error.Thank you for your excellent work!
```
1 designs to analyze.
Using 1 processes
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/home/yueyang/miniconda3/envs/diffusion/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/yueyang/miniconda3/envs/diffusion/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yueyang/miniconda3/envs/diffusion/lib/python3.9/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/yueyang/design_protein/heme_binder_diffusion//scripts/diffusion_analysis/process_diffusion_outputs.py", line 552, in process
    pose = read_pose_from_str_and_fix_issues(pdbfile, trb)
  File "/home/yueyang/design_protein/heme_binder_diffusion//scripts/diffusion_analysis/process_diffusion_outputs.py", line 141, in read_pose_from_str_and_fix_issues
    pyrosetta.rosetta.core.import_pose.pose_from_pdbstring(pose3, "\n".join(new_pdb))
RuntimeError: 

File: /home/benchmark/rosetta/source/src/core/kinematics/Stub.cc:106
Error in Stub::from_four_points(): 

File: /home/benchmark/rosetta/source/build/PyRosetta/Linux-5.4.0-84-generic-x86_64-with-glibc2.17/clang-3.4.2/python-3.9/release.serialization.thread/source/src/numeric/xyzVector.hh:654
Cannot create normalized xyzVector from vector of length() zero.  Error occurred when trying to normalize the vector between points A and B.  A=[0.000000,0.000000,0.000000], B=[0.000000,0.000000,0.000000].
Sorting the matches took 2.108 seconds.
  chainbreak loop_frac  ... SASA_exposed_atoms                                description
0        NaN       NaN  ...                NaN  2bxh_IIIA_IOS/out/2bxh_IIIA_IOS_dif_0.pdb
1        NaN       NaN  ...                NaN                                        NaN
2        NaN       NaN  ...                NaN                                        NaN
3        NaN       NaN  ...                NaN                                        NaN
4        NaN       NaN  ...                NaN                                        NaN
```
7o2g_HBA_dif_0.pdb
```
ATOM      6  N   GLU A   2      13.242 -14.345  17.058  1.00  0.00
ATOM      7  CA  GLU A   2      14.025 -13.753  15.980  1.00  0.00
ATOM      8  C   GLU A   2      13.124 -13.117  14.929  1.00  0.00
ATOM      9  O   GLU A   2      13.624 -12.264  14.185  1.00  0.00
ATOM     10  CB  GLU A   2       0.000   0.000   0.000  1.00  0.00
ATOM     11  CG  GLU A   2       0.000   0.000   0.000  1.00  0.00
ATOM     12  CD  GLU A   2       0.000   0.000   0.000  1.00  0.00
ATOM     13  OE1 GLU A   2       0.000   0.000   0.000  1.00  0.00
ATOM     14  OE2 GLU A   2       0.000   0.000   0.000  1.00  0.00
```
My pdb
```
ATOM      6  N   LYS A   2      13.070  -4.442 -14.321  1.00  0.00
ATOM      7  CA  LYS A   2      12.310  -3.351 -14.920  1.00  0.00
ATOM      8  C   LYS A   2      13.044  -2.024 -14.776  1.00  0.00
ATOM      9  O   LYS A   2      13.121  -1.466 -13.674  1.00  0.00
ATOM     10  CB  LYS A   2       0.000   0.000   0.000  1.00  0.00
ATOM     11  CG  LYS A   2       0.000   0.000   0.000  1.00  0.00
ATOM     12  CD  LYS A   2       0.000   0.000   0.000  1.00  0.00
ATOM     13  CE  LYS A   2       0.000   0.000   0.000  1.00  0.00
ATOM     14  NZ  LYS A   2       0.000   0.000   0.000  1.00  0.00
```
Thanks for your reply and have a good day!

**Comment by ikalvet** [comment]
That is actually a very puzzling error that I have not been able to reproduce.
I can tell from the trace that this script is failing in the function that is supposed to sort out the issues with the 0.00 0.00 0.00 coordinates.
I wonder I have omitted some residue types in line 124 of the script `scripts/diffusion_analysis/process_diffusion_outputs.py`
Perhaps try changing line 124 to this:
`if l.split()[3] in ["VAL", "GLN", "ARG", "LYS", "GLU", "ASN", "ASP", "MET", "PRO", "ILE", "LEU", "HIS", "THR"]:`

This function there is basically remedying the fact that AAdiffusion sometimes tries to "design" a sequence onto the generated backbone, but it does not produce any sidechains for those amino acids, and instead just sets the coordinates of each atom beyond Cbeta to 0.00. That however causes huge problems for PyRosetta at pose creation stage. So instead I made it so that all of those "designed" bigger residues get mutated to GLY by directly editing the PDB contents.

**Comment by samholtzen** [comment]
I ran into this problem a while back, and it was an error with addition of hydrogens to my small molecule ligand I wanted to create a backbone around. I was creating a ligand from a PDB file using RDKit to add hydrogens, but for some reason, there was an issue where the RDKit didn't assign coordinates for the hydrogens, so they all clustered at (0,0,0). Once I switched to OpenBabel and .sdf files for ligand processing, the problem went away because the hydrogens were given coordinates natively. Perhaps this workaround will help in the future?

**Comment by Salome321** [comment]
Hi, I'm running into the same error when trying to create a backbone around my small molecule. I'm adding the hydrogens in my theozyme using OpenBabel, but RFDiffusion_all_atom removes the hydrogens in the ligand when generating diffusion outputs. Did you solve this issue by adding back hydrogens afterwards?
Thank you in advance for your answer!

**Comment by samholtzen** [comment]
Hi all, revisiting this to help others who are having this problem. I've adapted my response from an email to @Salome321 and I hope it makes sense to everyone looking for a solution.

This error is thrown by the Rosetta framework, which is hard to debug. After much trial and error, I found that the problem lies in how I was generating the params file and input PDB. When analyzing a backbone, the structure is read from a PDB file into a Pose object. Since the PDB file contains the ligand, Rosetta must receive instructions on how to treat this ligand. The developers chose to incorporate it by calling it as a “noncanonical amino acid.” Rosetta uses something called a “params” file to do this. This file contains information about atoms, electronegativities, and bond angles. When PyRosetta is initialized in the `process_diffusion_outputs.py` file at line 439, it incorporates `{extra_res_fa}`, which is the directory of the params file. This allows PyRosetta to incorporate this “noncanonical amino acid” (i.e., your ligand) into its lexicon.
 
The way you generate the “params” file is crucial and MUST be made after adding hydrogens using OpenBabel. OpenBabel itself can be tricky. I’ve had success importing an SDF file, adding hydrogens with OpenBabel (pH 7.0), then generating the params file. I've found that doing this programmatically makes the process reproducible. In my [fork](https://github.com/samholtzen/heme_binder_diffusion), I have a Jupyter notebook that does exactly this (`prepare_params.ipynb`). Feel free to download the notebook and amend it to your needs. You should only need the first two code cells for what you’re doing (the rest is just for my own purpose). You can ignore the “Steps before this script” part, too.
 
I assume you have a file containing the structure of your ligand. This should be in the SDF format. I haven't tried it with a PDB file, but if you do, make sure to remove all amino acid information (lines that start with "ATOM") and change the line that imports the PDB to match the `.pdb` extension. I would suggest doing the following:
 
1. Clone the Rosetta repo locally and find the `molfile2params.py` file. It’s located in rosetta/source/scripts/python/public. This script generates the params file from your PDB file with protons. You’ll call this in the second cell of the notebook, so make sure you edit the path pointing to this file in the notebook.
2. Put your SDF containing your ligand in a folder named with three capital letters corresponding to your ligand (for heme, it’s HBA, for glucose, it’s GLC, etc).
3. Run the first cell of the notebook:
a. Change the `ligand` variable to what you named the folder above.
b. Change the `rosetta_dir` variable to the directory where the `molfile2params.py` file is stored.
4. Run the second cell of the notebook:
a. This will create the params file and the associated PDB file containing your ligand.
b. It will also move it to the `inout_dir`.
5. Since your new PDB file only contains your ligand, RFDiffusionAA won't accept it. You will have to add lines that contain at least one amino acid above the lines that describe your ligand. I just did a single alanine residue (code cell 5, ALA.pdb not included).

**Comment by ikalvet** [comment]
Thank you @samholtzen that's a very accurate and helpful response!

I realize that I have perhaps built this workflow to be too dependent on pyrosetta and its ecosystem. It's certainly possible to rebuild the diffusion-MPNN-af2 steps without it and using RDkit or openbabel to do all of the heavy lifting with the ligand. But there were many enzyme design specific aspects that necessitated pyrosetta for this example.

**Comment by Salome321** [comment]
Thank you very much @samholtzen for the very clear answer! This solved the issue for me. 

On another note, I also ran into some pyrosetta.import_pose.pose_from_pdbstring errors (too many tries in fill_missing_atoms). I solved it by making sure the atom names in the newly generated ligand param file were the same as the ones in the input / output files. I think molfile2params.py sometimes changes atom names when generating the param files. Maybe this could help someone with the same issue!
