### ISSUE TITLE
[Analyzing diffusion outputs] error: argument --pdb: expected at least one argument. No such file or directory: diffusion_analysis.sc

### ISSUE THREAD

**Issue by Lyueyang2020** [ikalvet/heme_binder_diffusion#8]
Hello, I am using your pipeline to design hemoglobin binding protein. When I run the code segment "Analyzing diffusion outputs," I encounter the following error. Thank you very much for your help.
```
process_diffusion_outputs.py: error: argument --pdb: expected at least one argument
FileNotFoundError: [Errno 2] No such file or directory: '/heme_binder_diffusion/outputs_lyy/live/0_diffusion/diffusion_analysis.sc'
```
```
### Analyzing diffusion outputs for clashes, ligand burial and scaffold quality
## If it's running too slowly consider increasing --nproc

analysis_script = f"{SCRIPT_DIR}/scripts/diffusion_analysis/process_diffusion_outputs.py"

diffusion_outputs = []
for d in diffusion_rundirs:
    diffusion_outputs += glob.glob(f"{d}/out/*.pdb")

# By default I don't use the --analyze flag. As a result the backbones are filtered as the script runs.
# You can set --analyze to True to calculate all scores for all backbones.
# This will slow the analysis down, but you can then filter the backbones separately afterwards.
dif_analysis_cmd_dict = {"--pdb": " ".join(diffusion_outputs),
                        "--ref": f"{SCRIPT_DIR}/input/*.pdb",
                        "--params": " ".join(params),
                        "--term_limit": "15.0",
                        "--SASA_limit": "0.3",  # Highest allowed relative SASA of ligand
                        "--loop_limit": "0.4",  # Fraction of backbone that can be loopy
                        "--ref_catres": "A15",  # Position of CYS in diffusion input
                        "--rethread": True,
                        "--fix": True,
                        "--exclude_clash_atoms": "O1 O2 O3 O4 C5 C10",  # Ligand atoms excluded from clashchecking because they are flexible
                        "--ligand_exposed_atoms": "C45 C46 C47",  # Ligand atoms that need to be more exposed
                        "--exposed_atom_SASA": "10.0",  # minimum absolute SASA for exposed ligand atoms
                        "--longest_helix": "30",
                        "--rog": "30.0",
                        "--partial": None,
                        "--outdir": None,
                        "--traj": "5/30",  # Also random 5 models are taken from the last 30 steps of the diffusion trajectory
                        "--trb": None,
                        "--analyze": False,
                        "--nproc": "1"}

analysis_command = f"{PYTHON['general']} {analysis_script}"
for k, val in dif_analysis_cmd_dict.items():
    if val is not None:
        if isinstance(val, list):
            analysis_command += f" {k}"
            analysis_command += " " + " ".join(val)
        elif isinstance(val, bool):
            if val == True:
                analysis_command += f" {k}"
        else:
            analysis_command += f" {k} {val}"
        print(k, val)

if len(diffusion_outputs) < 100:
    ## Analyzing locally
    p = subprocess.Popen(analysis_command, shell=True)
    (output, err) = p.communicate()
else:
    ## Too many structures to analyze.
    ## Running the analysis as a SLURM job.
    submit_script = "submit_diffusion_analysis.sh"
    utils.create_slurm_submit_script(filename=submit_script, name="diffusion_analysis",
                                     mem="8g", N_cores=dif_analysis_cmd_dict["--nproc"], time="0:20:00", email=EMAIL,
                                     command=analysis_command, outfile_name="output_analysis")

diffused_backbones_good = glob.glob(f"{DIFFUSION_DIR}/filtered_structures/*.pdb")

dif_analysis_df = pd.read_csv(f"{DIFFUSION_DIR}/diffusion_analysis.sc", header=0, sep="\s+")
```
```
--pdb 
--ref /home/yueyang/design_protein/heme_binder_diffusion//input/*.pdb
--params /home/yueyang/design_protein/heme_binder_diffusion//theozyme/HBA/HBA.params
--term_limit 15.0
--SASA_limit 0.3
--loop_limit 0.4
--ref_catres A15
--rethread True
--fix True
--exclude_clash_atoms O1 O2 O3 O4 C5 C10
--ligand_exposed_atoms C45 C46 C47
--exposed_atom_SASA 10.0
--longest_helix 30
--rog 30.0
--traj 5/30
--analyze False
--nproc 1
usage: process_diffusion_outputs.py [-h] --pdb PDB [PDB ...]
                                    [--trb TRB [TRB ...]]
                                    [--ref REF [REF ...]] [--analyze] [--fix]
                                    [--traj TRAJ] [--rethread]
                                    [--params PARAMS [PARAMS ...]]
                                    [--SASA_limit SASA_LIMIT]
                                    [--loop_limit LOOP_LIMIT]
                                    [--longest_helix LONGEST_HELIX]
                                    [--rog ROG] [--term_limit TERM_LIMIT]
                                    [--exclude_clash_atoms EXCLUDE_CLASH_ATOMS [EXCLUDE_CLASH_ATOMS ...]]
                                    [--ligand_exposed_atoms LIGAND_EXPOSED_ATOMS [LIGAND_EXPOSED_ATOMS ...]]
                                    [--exposed_atom_SASA EXPOSED_ATOM_SASA]
                                    [--ref_catres REF_CATRES [REF_CATRES ...]]
                                    [--loop_catres] [--outdir OUTDIR]
                                    [--partial] [--nproc NPROC]
process_diffusion_outputs.py: error: argument --pdb: expected at least one argument
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[27], [line 75](vscode-notebook-cell:?execution_count=27&line=75)
     [69](vscode-notebook-cell:?execution_count=27&line=69)     utils.create_slurm_submit_script(filename=submit_script, name="diffusion_analysis",
     [70](vscode-notebook-cell:?execution_count=27&line=70)                                      mem="8g", N_cores=dif_analysis_cmd_dict["--nproc"], time="0:20:00", email=EMAIL,
     [71](vscode-notebook-cell:?execution_count=27&line=71)                                      command=analysis_command, outfile_name="output_analysis")
     [73](vscode-notebook-cell:?execution_count=27&line=73) diffused_backbones_good = glob.glob(f"{DIFFUSION_DIR}/filtered_structures/*.pdb")
---> [75](vscode-notebook-cell:?execution_count=27&line=75) dif_analysis_df = pd.read_csv(f"{DIFFUSION_DIR}/diffusion_analysis.sc", header=0, sep="\s+")

File [~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1026](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1026), in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)
   [1013](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1013) kwds_defaults = _refine_defaults_read(
   [1014](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1014)     dialect,
   [1015](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1015)     delimiter,
   (...)
   [1022](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1022)     dtype_backend=dtype_backend,
   [1023](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1023) )
   [1024](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1024) kwds.update(kwds_defaults)
-> [1026](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:1026) return _read(filepath_or_buffer, kwds)

File [~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:620](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:620), in _read(filepath_or_buffer, kwds)
    [617](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:617) _validate_names(kwds.get("names", None))
    [619](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:619) # Create the parser.
--> [620](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:620) parser = TextFileReader(filepath_or_buffer, **kwds)
    [622](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:622) if chunksize or iterator:
    [623](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/parsers/readers.py:623)     return parser
...
    [880](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/common.py:880)     else:
    [881](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/common.py:881)         # Binary mode
    [882](https://vscode-remote+ssh-002dremote-002b192-002e168-002e1-002e161.vscode-resource.vscode-cdn.net/home/yueyang/design_protein/heme_binder_diffusion/~/miniconda3/envs/diffusion/lib/python3.9/site-packages/pandas/io/common.py:882)         handle = open(handle, ioargs.mode)

FileNotFoundError: [Errno 2] No such file or directory: '/home/yueyang/design_protein/heme_binder_diffusion/outputs_lyy/live/0_diffusion/diffusion_analysis.sc'
```

**Comment by Lyueyang2020** [comment]
And I don't know what this paragraph means, could you explain it in detail? Thank you
```
## If you're done with diffusion and happy with the outputs then mark it as done
DIFFUSION_DIR = f"{WDIR}/0_diffusion"
os.chdir(DIFFUSION_DIR)

if not os.path.exists(DIFFUSION_DIR+"/.done"):
    with open(f"{DIFFUSION_DIR}/.done", "w") as file:
        file.write(f"Run user: {username}\n")
```

**Comment by ikalvet** [comment]
Thank you for giving it a shot!
The "number of prcesses" error is a result of me doing a silly assumption on line 841 of the "process_diffusion_outputs.py" script. I fixed that issue and uploaded it.

Presumably this would also fix the "FileNotFoundError", which I assume arose from the fact that the analsyis script didn't produce an outputfile, and then the next command in the cell couldn't find the expected input.

**Comment by ikalvet** [comment]
> And I don't know what this paragraph means, could you explain it in detail? Thank you
> 
> ```
> ## If you're done with diffusion and happy with the outputs then mark it as done
> DIFFUSION_DIR = f"{WDIR}/0_diffusion"
> os.chdir(DIFFUSION_DIR)
> 
> if not os.path.exists(DIFFUSION_DIR+"/.done"):
>     with open(f"{DIFFUSION_DIR}/.done", "w") as file:
>         file.write(f"Run user: {username}\n")
> ```

The purpose of this kind of cell was to just create a file in the the run-directory of each step to indicate that this step is finished. If you end up reloading that notebook repeatedly and re-run the cells from the top then it would skip over these computationally expensive steps. For instance, if you're at step 3, and the notebook closed for some reason, then re-running the "Step 0" cell wouldn't just go and re-run the whole diffusion job, if it's marked as "done". I know it's not the most elegant implementation, but it get's the job done I suppose.

**Comment by Lyueyang2020** [comment]
> Thank you for giving it a shot! The "number of prcesses" error is a result of me doing a silly assumption on line 841 of the "process_diffusion_outputs.py" script. I fixed that issue and uploaded it.
> 
> Presumably this would also fix the "FileNotFoundError", which I assume arose from the fact that the analsyis script didn't produce an outputfile, and then the next command in the cell couldn't find the expected input.

Thank you for your reply, it no longer reports the above. But there is a new problem, I'm not quite sure if it's something I'm doing wrong, in the “process_diffusion_outputs.py” script at line 297 

```
“ if count == random.
        traj_ids_to_save = list(range(0, traj_N_save+1))
    else: traj_ids_to_save
        traj_ids_to_save = []
        # Figuring out <traj_N_save> random unique step id's
        while len(traj_ids_to_save) < random.
            random_id = np.random.randint(1, count)
            if random_id not in traj_ids_to_save.
                traj_ids_to_save.append(random_id)” 
```
shows that ‘traj_N_save’ is undefined. 
And my output structure shows the following:
```
200 designs to analyze.
Using 1 processes
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/home/yueyang/miniconda3/envs/diffusion/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/yueyang/miniconda3/envs/diffusion/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yueyang/miniconda3/envs/diffusion/lib/python3.9/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/yueyang/design_protein/heme_binder_diffusion//scripts/diffusion_analysis/process_diffusion_outputs.py", line 553, in process
    pose = pyr.pose_from_file(pdbfile)
RuntimeError: 

File: /home/benchmark/rosetta/source/src/core/kinematics/Stub.cc:106
Error in Stub::from_four_points(): 

File: /home/benchmark/rosetta/source/build/PyRosetta/Linux-5.4.0-84-generic-x86_64-with-glibc2.17/clang-3.4.2/python-3.9/release.serialization.thread/source/src/numeric/xyzVector.hh:654
Cannot create normalized xyzVector from vector of length() zero.  Error occurred when trying to normalize the vector between points A and B.  A=[0.000000,0.000000,0.000000], B=[0.000000,0.000000,0.000000].
Sorting the matches took 2.239 seconds.
    chainbreak loop_frac longest_helix  ... SASA SASA_rel                                  description
0          NaN       NaN           NaN  ...  NaN      NaN  2bxh_IIIA_IOS/out/2bxh_IIIA_IOS_dif_112.pdb
1          NaN       NaN           NaN  ...  NaN      NaN                                          NaN
2          NaN       NaN           NaN  ...  NaN      NaN                                          NaN
3          NaN       NaN           NaN  ...  NaN      NaN                                          NaN
4          NaN       NaN           NaN  ...  NaN      NaN                                          NaN
..         ...       ...           ...  ...  ...      ...                                          ...
195        NaN       NaN           NaN  ...  NaN      NaN                                          NaN
196        NaN       NaN           NaN  ...  NaN      NaN                                          NaN
197        NaN       NaN           NaN  ...  NaN      NaN                                          NaN
198        NaN       NaN           NaN  ...  NaN      NaN                                          NaN
199        NaN       NaN           NaN  ...  NaN      NaN                                          NaN

[200 rows x 11 columns]
```
I don't know what's wrong with it. Thanks for your guidance.
